import { CardStackIcon, DashboardIcon } from "@radix-ui/react-icons";
import {
    Calendar,
    CalendarCheck,
    FileQuestion,
    History,
    LocateIcon,
    Mail,
    UserCircle,
    UserPlus2,
    Users,
    Users2,
    Users2Icon,
} from "lucide-react";
import { BiError } from "react-icons/bi";
import { FaMicrophone } from "react-icons/fa";
import { GrEmergency } from "react-icons/gr";
import { MdBloodtype } from "react-icons/md";
import { create } from "zustand";

export const usePagesStore = create((set) => ({
    pages: [
        {
            title: "Dashboard",
            path: "/admin",
            icon: "📊",
            has_child: false,
        },
        {
            title: "Profile",
            path: "/admin/profile",
            icon: "👤",
            has_child: false,
        },
        {
            title: "Form Responses",
            path: "/admin/reports",
            icon: "📄",
            has_child: false,
        },
        {
            title: "Data Requests",
            path: "/admin/requests",
            icon: <FileQuestion />,
            has_child: false,
        },
        {
            title: "Users List",
            path: "/users",
            icon: <Users2 />,
            has_child: false,
        },
        {
            title: "New User",
            path: "/users/create",
            icon: <UserPlus2 />,
            has_child: false,
        },
        {
            title: "Error page",
            path: "/auth/error",
            icon: <BiError />,
            has_child: false,
        },
        {
            title: "System Administation",
            path: "#",
            icon: "⚙️",
            has_child: true,
            child: [
                {
                    title: "Users Management",
                    path: "/admin/users",
                    icon: <Users />,
                },
                // {
                //     title: "Medication Errors",
                //     path: "/admin/error_types",
                //     icon: <MdMedication />,
                // },
            ],
        },
    ],
    setPages: (newPages) => set({ pages: newPages }), // Optional if you need to modify `pages`
    breadcrumbs: [],
    setBreadcrumbs: (newBreadcrumbs) => set({ breadcrumbs: newBreadcrumbs }),
    menus: [
        {
            title: "Dashboard",
            path: "/",
            icon: <DashboardIcon />,
            roles: [
                "Admin",
                "Donor",
                "Developer",
                "Agency Administrator",
                "Organizer",
            ],
            has_child: false,
            is_role_based: true,
            children: [
                {
                    title: "Analytics",
                    path: "/dashboard/analytics",
                    icon: "analytics-icon",
                    is_role_based: true,
                    roles: [
                        "Admin",
                        "Donor",
                        "Developer",
                        "Agency Administrator",
                        "Organizer",
                    ],
                },
            ],
        },
        {
            title: "Profile",
            path: "/profile",
            icon: <UserCircle />,
            roles: [
                "Admin",
                "Donor",
                "Developer",
                "Agency Administrator",
                "Organizer",
            ],
            is_role_based: true,
            has_child: false,
        },

        {
            title: "Blood Donations",
            path: "/blood-collections",
            icon: <MdBloodtype />,
            roles: ["Admin"],
            is_role_based: true,
            has_child: false,
        },
        {
            title: "Blood Drives",
            path: "/events",
            icon: <CalendarCheck />,
            roles: ["Admin", "Developer", "Agency Administrator", "Organizer"],
            is_role_based: true,
            has_child: false,
        },
        {
            title: "Appointments",
            path: "/appointments",
            icon: <Calendar />,
            roles: ["Admin"],
            is_role_based: true,
            has_child: false,
        },
        {
            title: "My Appointments",
            path: "/donor-appointments",
            icon: <Calendar />,
            roles: ["Donor"],
            is_role_based: true,
            has_child: false,
        },
        {
            title: "Blood Drives",
            path: "/events",
            icon: <LocateIcon />,
            roles: ["Donor"],
            is_role_based: true,
            has_child: false,
        },
        {
            title: "View Donor Card",
            path: "/donor-card",
            icon: <CardStackIcon />,
            roles: ["Donor"],
            is_role_based: true,
            has_child: false,
        },
        {
            title: "Announcements",
            path: "/announcements",
            icon: <FaMicrophone />,
            roles: ["Admin", "Developer", "Agency Administrator", "Organizer"],
            is_role_based: true,
            has_child: false,
        },
        {
            title: "Agencies Management",
            path: "/agencies",
            icon: <Users />,
            roles: ["Admin"],
            is_role_based: true,
            has_child: false,
        },
        {
            title: "Donors Management",
            path: "/donors",
            icon: <UserPlus2 />,
            roles: ["Admin", "Developer", "Agency Administrator", "Organizer"],
            is_role_based: true,
            has_child: false,
        },
        {
            title: "Emergency Requests",
            path: "/emergency-requests",
            icon: <GrEmergency />,
            roles: ["Admin", "Developer", "Agency Administrator", "Organizer"],
            is_role_based: true,
            has_child: false,
        },
        // {
        //     title: "Blood Requests",
        //     path: "/blood-requests",
        //     icon: <MdOutlineBloodtype />,
        //     roles: ["Donor"],
        //     is_role_based: true,
        //     has_child: false,
        // },
        {
            title: "Manage Coordinators",
            path: "/manage-coordinators",
            icon: <Users2Icon />,
            roles: ["Developer", "Agency Administrator"],
            is_role_based: true,
            has_child: false,
        },
        {
            title: "Coordinators",
            path: "/coordinators",
            icon: <Users2Icon />,
            roles: ["Admin", "Developer"],
            is_role_based: true,
            has_child: false,
        },
        {
            title: "System Administation",
            path: "#",
            icon: "⚙️",
            roles: ["Admin", "Developer"],
            has_child: true,
            is_role_based: true,
            child: [
                {
                    title: "Users Management",
                    path: "/portal/admin/users",
                    icon: <Users />,
                    roles: ["Admin", "Developer"],
                    has_child: false,
                    is_role_based: true,
                },
                {
                    title: "Email Notifications",
                    path: "/portal/admin/email-notifications",
                    icon: <Mail />,
                    roles: ["Admin"],
                    has_child: false,
                    is_role_based: true,
                },
                {
                    title: "Audit Trails",
                    path: "/portal/admin/audit-trails",
                    icon: <History />,
                    roles: ["Admin"],
                    has_child: false,
                    is_role_based: true,
                },
            ],
        },
    ],
}));
