name: Deploy to Staging
on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            # 1️⃣ Fetch the latest code from GitHub
            - uses: actions/checkout@v4

            # 2️⃣ Install dependencies
            - name: Install dependencies
              run: npm ci

            # 3️⃣ Build the Next.js project
            - name: Build project
              run: npm run build

            # 4️⃣ Restart your PM2 app (same as your manual command)
            - name: Restart PM2 app
              run: pm2 restart BLOOD-BANK-PORTAL --update-env || pm2 start npm --name BLOOD-BANK-PORTAL -- run start

            # 5️⃣ Purge Cloudflare cache automatically
            - name: Purge Cloudflare cache
              env:
                  CLOUDFLARE_ZONE_ID: b28c36e1ee2b5d9e1bac62acfcdd25d7
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
              run: |
                  curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
                    -H "Content-Type: application/json" \
                    -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
                    --data '{"purge_everything":true}'
