name: Deploy to Staging
on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            # 1️⃣ Fetch the latest code from GitHub into the runner's _work directory
            - uses: actions/checkout@v4

            # 2️⃣ Install dependencies (clean install)
            - name: Install dependencies
              run: npm ci

            # 3️⃣ Build the Next.js project
            - name: Build project
              run: npm run build

            # 4️⃣ Deploy built project to your production directory
            - name: Deploy to production directory
              run: |
                  rsync -av --delete . /home/mroman/projects/blood-donation-app/

            # 5️⃣ Restart PM2 app from the production directory
            - name: Restart PM2 app
              working-directory: /home/mroman/projects/blood-donation-app
              run: |
                  pm2 restart BLOOD-BANK-PORTAL --update-env || \
                  pm2 start npm --name BLOOD-BANK-PORTAL -- run start

            # 6️⃣ Purge Cloudflare cache automatically
            - name: Purge Cloudflare cache
              env:
                  CLOUDFLARE_ZONE_ID: b28c36e1ee2b5d9e1bac62acfcdd25d7
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
              run: |
                  curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
                    -H "Content-Type: application/json" \
                    -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
                    --data '{"purge_everything":true}'
